### ISSUE TITLE
CMS user can add a new searchable register to the sitetree

### ISSUE THREAD

**Issue by rupachup** [silverstripe/silverstripe-ckan-registry#2]
## User story
As a CMS User 
I want to be able to create a searchable register in the CMS
So I am not dependent on a developer to implement a register search.

## Acceptance criteria

- [x] [CMS User can add a data register search page in the sitetree](https://github.com/silverstripe/silverstripe-ckan-registry/issues/19)
- [x] CMS User can specify which CKAN dataset resource the interface will search by providing it's unique resource ID number.
- [x] [The user can provide directly the resource ID or the URL to the dataset and select from available](https://github.com/silverstripe/silverstripe-ckan-registry/issues/17).
- [x] If they directly specify a resource ID, the page type will keep tabs on which dataset URL it's from (needed for the reference link back later on). 
- [x] [Page will become aware of the available columns in the resource and display to the user](https://github.com/silverstripe/silverstripe-ckan-registry/issues/18).
- [x] [CMS User can select which columns will display in the register search results for the end user](https://github.com/silverstripe/silverstripe-ckan-registry/issues/20).
- [x] [CMS user can select if the data will be shown in a detail view of the data](https://github.com/silverstripe/silverstripe-ckan-registry/issues/21).
- [x] CMS User can give the interface a title and description (to provide context to the end user, this is just the standard title/content of SS pages).
- [x] [CMS User can provide a pre-filter for a column so that certain data is never returned to the end user (include or exclude). Only 1 condition is required to start.](https://github.com/silverstripe/silverstripe-ckan-registry/issues/23)
- [x] User can provide a new label to a column (alias)
- [x] **Nice to have**: CMS User can set the number of items to show for pagination (initial version we could just cap this at X per page or CMS admin can define how to cap the returned results e.g. by date range, items... ) (note: this is included in #19)

**Comment by robbieaverill** [comment]
>User can provide a new label to a column (alias)

@brynwhyman I wonder whether we could bundle this into the "Readable label" column and make it the same thing? We could auto-generate the readable label value on import from the original label, but allow users to modify it for the frontend

**Comment by NightJar** [comment]
Last outstanding issue is actually #23 so I'm going to just close this.
