### ISSUE TITLE
CMS user can configure filters for a dataset for the end user

### ISSUE THREAD

**Issue by rupachup** [silverstripe/silverstripe-ckan-registry#3]
## User story
As a CMS User adding a register search
I can add 1 or more predefined filter types and configure the way they interact with the search query
So that end users are able to refine their queries.

## Acceptance criteria

- [x] [CMS user can add a filter from a preset list of filter types.](https://github.com/silverstripe/silverstripe-ckan-registry/issues/24)
- [x] CMS User can provide a title for any filter added and this is displayed to the user.
- [x] CMS User can select the order in which these filter appear to the end user.
- [ ] [CMS User can assign on which dataset column the filter will be active.](https://github.com/silverstripe/silverstripe-ckan-registry/issues/25)
- [ ] This is about setting up the pattern for adding filters in the CMS and not adding all the filters.
- [ ] [When a new data resource is added, a filter is also added that will search across all columns by default (makes having a basic searchable register very easy).](https://github.com/silverstripe/silverstripe-ckan-registry/issues/27)

Initial set of filters would be: text, dropdown, checkbox (boolean).

[Styleguide](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5bc50dab5fac6b001175391f)

**Comment by NightJar** [comment]
> This is about setting up the pattern for adding filters in the CMS and not adding all the filters

I don't understand this one.

All other issues addressed. Closing - reopen possible if someone wants to explain the point above and contests it as not being done :)

**Comment by camfindlay** [comment]
@NightJar that comment was just saying that you dont have to implement the actual filter objects here... just set up a way of doing that (and a way for someone in the future to be able to follow a coding pattern to add new filter types).

**Comment by NightJar** [comment]
sweet, well that's done then, cheers!

To expand:
We have a `ResourceFilter` class, in a similar fashion to SilverStripe's `FormField`, of which the default render is a `TextField`. Subclasses are free to be added and they'll automatically show up in the filter list - the example in this module being the `ResourceFilter\Dropdown` (probably more akin to `silverstripe/userforms` `EditableFormField` really).
